flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- binary-0.8.5.1
- directory-1.3.1.5
- unix-2.7.2.2
- aeson-1.2.3.0
- extra-1.6
- megaparsec-6.4.0
- parser-combinators-0.4.0
- websockets-0.11.2.0
- array-0.5.1.1
- pretty-terminal-0.1.0.0

resolver: lts-9.10
